[add] Pagination & [update] HomePage、EventPage、HistoryPage、Modal、variable
v61265/if-platform-frontend pull request #14
Opened 2021-01-28 14:07 UTC by kaochihyu

### What you do ? (Required)
#### 新增
* 在 component 新增 Pagination 

#### 變更
* HomePage：把 pagination 另存在 components、新增 pagination 按鈕的前端、修改大小區塊活動的前端
* EventPage：幫報名取消按鈕加上 Modal
* HistoryPage：
* Modal：新增 CheckModal，報名、取消活動確認用
* variable：新增 checkModalContent，報名、取消活動確認用

### How can I understand this PR ? (Required)
修改 event 的前端

2021-01-28 14:34 UTC, kaochihyu reviewed
event-front-end PR

2021-01-28 14:34 UTC, kaochihyu commented on src/components/Modal.js
> +};
EventPage 報名、取消活動確認用

2021-01-28 14:34 UTC, kaochihyu commented on src/components/Pagination.js
> +  let startPage;
Pagination 的 components

2021-01-28 14:34 UTC, kaochihyu commented on src/constants/variable.js
> +};
EventPage 報名、取消確認用

2021-01-28 14:34 UTC, kaochihyu commented on src/page/EventPage.js
> +        <Ps>{descriptionText}</Ps>
會議連結、音檔連結改成有連結才顯示

2021-01-28 14:34 UTC, kaochihyu commented on src/page/EventPage.js
> +import { textModalContent, checkModalContent } from "../constants/variable";
取消、報名活動用的 Modal、varaible

2021-01-28 14:34 UTC, kaochihyu commented on src/page/EventPage.js
> +
Modal 初始值

2021-01-28 14:34 UTC, kaochihyu commented on src/page/EventPage.js
>      </MaxPage>
判斷 Modal 要發送的 request

2021-01-28 14:34 UTC, kaochihyu commented on src/page/HistoryEventPage.js
>        </EventInfo>
有連結才顯示音檔連結、會議連結

2021-01-28 14:34 UTC, kaochihyu commented on src/page/HomePage.js
>  const Block = styled.div`
拿掉 pagination 的 style

2021-01-28 14:34 UTC, kaochihyu commented on src/page/HomePage.js
>    );
新增 EventDefault，沒有正在進行中的活動時會顯示

2021-01-28 14:34 UTC, kaochihyu commented on src/page/HomePage.js
> +
用來判斷 Pagination 及顯示的活動

2021-01-28 14:34 UTC, kaochihyu commented on src/page/HomePage.js
> +        />
修改區分進行中、已結束的活動

2021-02-06 07:40 UTC, cybershota commented on src/components/Pagination.js
> +  margin-bottom: ${({ theme }) => theme.space.md}px;
原來可以用 gap 學習了 🥺

2021-02-06 07:51 UTC, cybershota commented on src/page/EventPage.js
> +            <a href={event.meetingLink} target="_blank">
小心 target="_blank" 的[安全性問題](https://pjchender.blogspot.com/2020/05/relnoreferrer-targetblank.html)
不過有消息說 chrome 有[更改預設設定](https://twitter.com/aszx87410/status/1357903025210150912)了

2021-02-06 07:53 UTC, cybershota commented on src/page/EventPage.js
> +            <a href={event.meetingLink} target="_blank">
好像也可以用 <meta> 統一設定網站的 referrer
`<meta name="referrer" contnet="none">`

2021-02-06 08:41 UTC, cybershota commented on src/page/HomePage.js
> +  let itemsPerPage = 9;
WebAPI getEvents 的 limit 是 9，這樣好像永遠不會超過 9 需要分頁

2021-02-06 08:56 UTC, cybershota requested changes
在本機端測試時，分頁功能有些奇怪，我新增了總共 16 個混和了進行中與已結束的活動，但分頁只顯示一頁。原因應該是 WebAPI request limit 就是 9，然後分頁 offset 也是 9 且 offset 變數沒有用到，可能需要再檢查一下功能是否寫對。

有個想法：進行中的活動可以無止盡的出現在第一頁（進行中的應該不會多到哪去 🤔）然後第一頁的歷史活動最少 3 個，切到第二頁後只顯示 offset 的歷史活動，這樣頁面的顯示應該會清晰很多

2021-02-06 08:56 UTC, cybershota commented on src/page/HomePage.js
> +  let offset = itemsPerPage * (currentPage - 1);
本機端測試，offset 這個變數沒有用到

2021-02-06 08:56 UTC, cybershota commented on src/page/HomePage.js
> +  let totalEvents = eventsHistory.length;
totalEvents 是不是要加上 eventsInProcess.length

2021-02-06 08:56 UTC, cybershota commented on src/page/HomePage.js
> +  let totalEvents = eventsHistory.length;
或者只算歷史活動，多的歷史活動才分頁也行的

2021-02-06 09:04 UTC, kaochihyu commented on src/page/EventPage.js
> +            <a href={event.meetingLink} target="_blank">
了解！我再來改

2021-02-06 09:15 UTC, kaochihyu commented on src/page/HomePage.js
> +  let offset = itemsPerPage * (currentPage - 1);
我忘記刪了，感謝提醒~

2021-02-06 09:29 UTC, kaochihyu commented on src/page/HomePage.js
> +  let totalEvents = eventsHistory.length;
我的寫法是進行中活動就像前面你說的無止盡的出現在第一頁，然後分頁的部分只會依據歷史活動的數量來分(每九個就換頁)
WebAPI 的部份跟你發現的一樣 limit 有預設值，所以怎麼新增活動都只會是一頁(這個有跟生菜反應了><，請他幫我把 limit 的預設值去掉，去掉之後應該就會正常(?))

@cybershota  感謝批改~

2021-02-12 16:52 UTC, merged